export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const OBTENER_PRODUCTO = 'OBTENER_PRODUCTO';
export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO';
export const EDITAR_PRODUCTO_EXITO = 'EDITAR_PRODUCTO_EXITO';
export const EDITAR_PRODUCTO_DESACTUALIZADO = 'EDITAR_PRODUCTO_DESACTUALIZADO';
export const EDICION_COMPLETADA = 'EDICION_COMPLETADA';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const ELIMINAR_EXITO = 'ELIMINAR_EXITO';